### ISSUE TITLE
pip install jenkinsapi fails for v1.5

### ISSUE THREAD

**Issue by LarsNordin** [pycontribs/jenkinsapi#11]
pip install jenkinsapi
Downloading/unpacking jenkinsapi
  Downloading jenkinsapi-0.1.5.tar.gz
  Running setup.py egg_info for package jenkinsapi
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/build/jenkinsapi/setup.py", line 5, in <module>
        DESCRIPTION = open(os.path.join(PROJECT_ROOT, "README.rst")).read()
    IOError: [Errno 2] No such file or directory: '/root/build/jenkinsapi/README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/build/jenkinsapi/setup.py", line 5, in <module>

```
DESCRIPTION = open(os.path.join(PROJECT_ROOT, "README.rst")).read()
```

IOError: [Errno 2] No such file or directory: '/root/build/jenkinsapi/README.rst'

---

Command python setup.py egg_info failed with error code 1

**Comment by nitintt1991** [comment]
@LarsNordin This ran like cheese and butter. Thanks a lot
