### ISSUE TITLE
How to get console output

### ISSUE THREAD

**Issue by jakubczaplicki** [pycontribs/jenkinsapi#228]
I'd like to be able to analyse/parse a console output. How can I fetch the string of the console ?

**Comment by TwitchChen** [comment]
@jakubczaplicki 
hi, i used the same way,but get an error

`# encoding: utf-8

from jenkinsapi import jenkins,api
print(api.get_latest_build(username='admin', password='admin123',jenkinsurl='http://192.168.102.206:8080',jobname="demo",ssl_verify=False))
b = api.get_build(username='admin', password='admin123',jenkinsurl='http://192.168.102.206:8080',jobname="demo",build_no='demo #2',ssl_verify=False)
print(b.get_console())`
`demo #2
Traceback (most recent call last):
  File "/Users/twitch/workspace/flask-gentelella/source/projects/test.py", line 29, in <module>
    b = api.get_build(username='admin', password='admin123',jenkinsurl='http://192.168.102.206:8080',jobname="demo",build_no='demo #2',ssl_verify=False)
  File "/Users/twitch/workspace/flask-gentelella/env/lib/python3.6/site-packages/jenkinsapi/api.py", line 67, in get_build
    return job.get_build(build_no)
  File "/Users/twitch/workspace/flask-gentelella/env/lib/python3.6/site-packages/jenkinsapi/job.py", line 393, in get_build
    assert isinstance(buildnumber, int)
AssertionError`

Can you do me a favor,thanks
