### ISSUE TITLE
"KeyError: location" when invoking a build job

### ISSUE THREAD

**Issue by conrosebraugh** [pycontribs/jenkinsapi#351]
I am running Jenkins version 1.596.1. When I try and start a build job, I get the following traceback:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    ahn.invoke(build_params=bp)
  File "/Users/crosebraugh-macbook-pro/jenkins/lib/python2.7/site-packages/jenkinsapi/job.py", line 210, in invoke
    redirect_url = response.headers['location']
  File "/Users/crosebraugh-macbook-pro/jenkins/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

I inspected the response object and, sure enough, there is no location header.

**Comment by lechat** [comment]
This feature have been added in more recent Jenkins versions. @salimfadhley shall we mention this in the README.rst?
