### ISSUE TITLE
Unable to get the QueueItem

### ISSUE THREAD

**Issue by bGorle** [pycontribs/jenkinsapi#407]
Unable to get the **QueueItem** either from **Job** object or from **Server** object.

and it is showing this error

```
Traceback (most recent call last):
  File "sample_jenkinsapi.py", line 68, in <module>
    queue_item = job_instance.get_queue_item()
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/job.py", line 421, in get_queue_item
    return QueueItem(self.jenkins, **self._data['queueItem'])
```

**Comment by lechat** [comment]
What is the error?

**Comment by gitthc** [comment]
File "C:\Python27\lib\site-packages\jenkinsapi\job.py", line 435, in get_queue_item
    return QueueItem(self.jenkins, **self._data['queueItem'])
TypeError: __init__() got an unexpected keyword argument 'task'

**Comment by MrKiven** [comment]
same issue...
