### ISSUE TITLE
how to use jenkinesapi.job.invoke to upload a file to server

### ISSUE THREAD

**Issue by zh794390558** [pycontribs/jenkinsapi#470]
My code like this :
```
data_file = open('<file_name>', 'r')
running_job_object = new_job.invoke(block=True,
                                build_params={'<para1>': '<value>', '<para2>': '<value>'},
                                files={'<file_para_name>': data_file})
data_file.close()
```

I can build without the 'files' parmeter, but add 'files' has something wrong such as below. 

Traceback (most recent call last):
  File "zjenkins.py", line 200, in <module>
    handle.build_job()
  File "zjenkins.py", line 180, in build_job
    mjob.invoke('xxxxxx', block=True, build_params=self.param[self.param['paramid']], files={'task.xml': file0})
  File "/home/zh/zjenkins/job.py", line 217, in invoke
    allow_redirects=False
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/utils/requester.py", line 135, in post_and_confirm_status
    response.url, data, headers, response.status_code, response.text.encode('UTF-8')))
jenkinsapi.custom_exceptions.JenkinsAPIException: Operation failed. url=http://***.***.***.***:8180/job/***/build?token=**** data={'json': '{"parameter": [{"name": "TARGET_BUILD", "value": "release"}, {"name": "TARGET_PLAT", "value": "x86"}, {"name": "TARGET_PROJECT", "value": "x86_32"}, {"name": "build_branch", "value": "v5"}, {"name": "task.xml", "file": "task.xml"}], "statusCode": "303"}', 'build_branch': 'dev_v5', 'TARGET_PROJECT': 'x86_32', 'TARGET_BUILD': 'release', 'TARGET_PLAT': 'x86'}, headers=None, status=500, text=

  <!DOCTYPE html><html><head resURL="/static/3853b666" data-rooturl="" data-resurl="/static/3853b666">
    
    <title>Jenkins [Jenkins]</title><link rel="stylesheet" href="/static/3853b666/css/layout-common.css" type="text/css" /><link rel="stylesheet" href="/static/3853b666/css/style.css" type="text/css" /><link rel="stylesheet" href="/static/3853b666/css/color.css" type="text/css" /><link rel="stylesheet" href="/static/3853b666/css/responsive-grid.css" type="text/css" /><link rel="shortcut icon" href="/static/3853b666/favicon.ico" type="image/vnd.microsoft.icon" /><link color="black" rel="mask-icon" href="/images/mask-icon.svg" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/3853b666";</script><script src="/static/3853b666/scripts/prototype.js" type="text/javascript"></script><script src="/static/3853b666/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/3853b666/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/3853b666/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/3853b666/scripts/yui/dom/dom-min.js"></script><script src="/static/3853b666/scripts/yui/event/event-min.js"></script><script src="/static/3853b666/scripts/yui/animation/animation-min.js"></script><script src="/static/3853b666/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/3853b666/scripts/yui/container/container-min.js"></script><script src="/static/3853b666/scripts/yui/connection/connection-min.js"></script><script src="/static/3853b666/scripts/yui/datasource/datasource-min.js"></script><script src="/static/3853b666/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/3853b666/scripts/yui/menu/menu-min.js"></script><script src="/static/3853b666/scripts/yui/element/element-min.js"></script><script src="/static/3853b666/scripts/yui/button/button-min.js"></script><script src="/static/3853b666/scripts/yui/storage/storage-min.js"></script><script src="/static/3853b666/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/3853b666/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("", "");</script><link rel="stylesheet" href="/static/3853b666/scripts/yui/container/assets/container.css" type="text/css" /><link rel="stylesheet" href="/static/3853b666/scripts/yui/assets/skins/sam/skin.css" type="text/css" /><link rel="stylesheet" href="/static/3853b666/scripts/yui/container/assets/skins/sam/container.css" type="text/css" /><link rel="stylesheet" href="/static/3853b666/scripts/yui/button/assets/skins/sam/button.css" type="text/css" /><link rel="stylesheet" href="/static/3853b666/scripts/yui/menu/assets/skins/sam/menu.css" type="text/css" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><script src="/adjuncts/3853b666/org/kohsuke/stapler/jquery/jquery.full.js" type="text/javascript"></script><script>var Q=jQuery.noConflict()</script><script src="/static/3853b666/scripts/yui/cookie/cookie-min.js"></script><link rel="stylesheet" href="" type="text/css" /><script src="" type="text/javascript"></script><script src="/static/3853b666/jsbundles/page-init.js" type="text/javascript"></script></head><body data-model-type="hudson.model.Hudson" id="jenkins" class="yui-skin-sam jenkins-2.11 two-column" data-version="2.11"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><div id="header"><div class="logo"><a id="jenkins-home-link" href="/"><img src="/static/3853b666/images/headshot.png" alt="title" id="jenkins-head-icon" /><img src="/static/3853b666/images/title.png" alt="title" width="139" id="jenkins-name-icon" height="34" /></a></div><div class="login"> <a href="/login?from=%2Fjob%2FUniChip_Force1.0_Build_Project_bak%2Fbuild"><b>log in</b></a>
    |
    <a href="/signup"><b>sign up</b></a></div><div class="searchbox hidden-xs"><form method="get" name="search" action="/search/" style="position:relative;" class="no-json"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input name="q" placeholder="search" id="search-box" class="has-default-text" /> <a href="http://wiki.jenkins-ci.org/display/JENKINS/Search+Box"><img src="/static/3853b666/images/16x16/help.png" style="width: 16px; height: 16px; " class="icon-help icon-sm" /></a><div id="search-box-completion"></div><script>createSearchBox("/search/");</script></div></form></div></div><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/adjuncts/3853b666/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/3853b666/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"></div><ul id="breadcrumbs"><li class="item"><a href="/" class="model-link inside">Jenkins</a></li><li href="/" class="children"></li></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></div></div><div id="page-body" class="clear"><div id="side-panel"><div class="task"><a href="http://jenkins-ci.org/" class="task-icon-link"><img src="/static/3853b666/images/24x24/next.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-next icon-md" /></a> <a href="http://jenkins-ci.org/" class="task-link">Jenkins project</a></div><div class="task"><a href="http://issues.jenkins-ci.org/" class="task-icon-link"><img src="/static/3853b666/images/24x24/gear2.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md" /></a> <a href="http://issues.jenkins-ci.org/" class="task-link">Bug tracker</a></div><div class="task"><a href="http://jenkins-ci.org/content/mailing-lists" class="task-icon-link"><img src="/static/3853b666/images/24x24/search.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-search icon-md" /></a> <a href="http://jenkins-ci.org/content/mailing-lists" class="task-link">Mailing Lists</a></div><div class="task"><a href="https://twitter.com/jenkinsci" class="task-icon-link"><img src="/static/3853b666/images/24x24/user.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-user icon-md" /></a> <a href="https://twitter.com/jenkinsci" class="task-link">Twitter: @jenkinsci</a></div></div><div id="main-panel"><a name="skip2content"></a><h1 style="text-align: center"><img src="/static/3853b666/images/rage.png" width="154" height="179" /><span style="font-size:50px"> Oops!</span></h1><div id="error-description"><p>A problem occurred while processing the request.
        Please check <a href="https://issues.jenkins-ci.org/">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="http://jenkins-ci.org/content/mailing-lists">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style="margin:2em; clear:both">javax.servlet.ServletException: java.lang.IllegalArgumentException: No such parameter definition: build_branch
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:233)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:140)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:82)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No such parameter definition: build_branch
	at hudson.model.ParametersDefinitionProperty._doBuild(ParametersDefinitionProperty.java:164)
	at jenkins.model.ParameterizedJobMixIn.doBuild(ParameterizedJobMixIn.java:195)
	at hudson.model.AbstractProject.doBuild(AbstractProject.java:1751)
	at hudson.model.AbstractProject.doBuild(AbstractProject.java:1757)
	at sun.reflect.GeneratedMethodAccessor710.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 59 more
</pre></div></div></div><footer><div class="container-fluid"><div class="row"><div class="col-md-6" id="footer"></div><div class="col-md-18"><span class="page_generated">Page generated: Aug 5, 2016 5:16:50 PM CST</span><span class="rest_api"><a href="api/">REST API</a></span><span class="jenkins_ver"><a href="http://jenkins-ci.org/">Jenkins ver. 2.11</a></span><div id="l10n-dialog" class="dialog"></div><div id="l10n-footer" style="display:none; float:left"><a href="#" onclick="return showTranslationDialog();"><img src="/static/3853b666/plugin/translation/flags.png" />
      Help us localize this page
    </a></div><script>var footer = document.getElementById('l10n-footer');
    var f = document.getElementById('footer');
    f.insertBefore(footer,f.firstChild);
    footer.style.display="block";

    var translation={}; 
    translation.bundles = "XrxU9sR8IG9IVZs9VXovConmhXYnmxcnynAgKb5fh1ZlL5iK8ZNeymxEgOZEaDLP0Vtr7QIDMPulhFdRdiSOTAbPzGpwpspdavRv29gr2nXZTbue2vrJ0GTetNmZ6IM8dF4lLA7xfWFgxo9mAFS2QLko20CzT4t0my7G1b/XkZ2/HWrv1kitO3c/czSi98X29DhElmpLfTu+ZKdwke89UYZgTfmPADGhLoHlouhRo80vtdyEqrl1PQrIMoIyQQfc1LmfeG6l3AjUj6etkCm7GpMMQeowtJKO7KWJJ+u9dTz7tvvfzR837s4/t2acVrd8iv5AX1jG9TTI1xJPltloC6wEBZaVUwNXrq44viJHTRFzI+FwMEcedHmC+hdhOpAX9eK1VeQEt/VmH4vTdnhbkzA6CqlZMmSKhMQruk19WGXXELvlODV0lvSFb8cBNFq1S7rW9TbpMhZBNZamc4ylo3aJRqBFLzLoUpovjZmfspA=";
    translation.detectedLocale = "";

    function showTranslationDialog() {
      if(!translation.launchDialog)
        loadScript("/static/3853b666/plugin/translation/dialog.js");
      else
        translation.launchDialog();
      return false; 
    }</script></div></div></div></footer></body></html>

**Comment by lechat** [comment]
This build complains that there is no "build_branch" parameter in job definition.

**Comment by lechat** [comment]
Here is example code, form tests:

```
    def test_invoke_job_with_file(self):
        file_data = random_string()
        param_file = StringIO(file_data)

        job_name = 'create1_%s' % random_string()
        job = self.jenkins.create_job(job_name, JOB_WITH_FILE)

        job.invoke(block=True, files={'file.txt': param_file})

        # Following test is enabled because standalone file parameters work

        build = job.get_last_build()
        while build.is_running():
            time.sleep(0.25)

        artifacts = build.get_artifact_dict()
        self.assertIsInstance(artifacts, dict)
        art_file = artifacts['file.txt']
        self.assertTrue(art_file.get_data().strip(), file_data)
```

**Comment by zh794390558** [comment]
@lechat Thank you for your attention. I have solve this probolem with changeing my commit parameters which should be uppercase. But, I have also encounter another problem like below, which job had successfully done:

Traceback (most recent call last):
  File "zjenkins.py", line 203, in <module>
    handle.build_job()
  File "zjenkins.py", line 183, in build_job
    mjob.invoke('xxxxx',block=True, build_params=self.param[self.param['paramid']], files={'task.xml': file0})
  File "/home/tangchen/zh/unisound/zjenkins/job.py", line 225, in invoke
    raise ValueError('Builds with file parameters are not '
ValueError: Builds with file parameters are not supported by this jenkinsapi version. Please use previous version.

This line below is always False:
`if not redirect_url.startswith("%s/queue/item" % self.jenkins.baseurl): `

**Comment by zh794390558** [comment]
@lechat Thank you very much, agin. I have solve the probelm above with upgrading jenkinsapi library to 0.3.0 version.
