### ISSUE TITLE
upload file in version 0.3.2

### ISSUE THREAD

**Issue by zh794390558** [pycontribs/jenkinsapi#487]
##### ISSUE TYPE
 - Bug Report

##### Jenkinsapi VERSION
0.3.2
##### Jenkins VERSION
1.653
##### SUMMARY
 mjob = job.Job(url=None, name=self.job_name, jenkins_obj=j)
 has_params() is not work well as version 0.3.0

##### EXPECTED RESULTS
when has not slef._data['actions'] is also can work well.
in version 0.3.0 is work well, but not now.

##### ACTUAL RESULTS
no 'action' label.

##### USEFUL INFORMATION
```
{'_class': 'hudson.model.Hudson',
 'jobs': [{'_class': 'hudson.model.FreeStyleProject',
           'color': 'red',
           'name': 'xxxxxxxx',
           'url': 'http://xxxxx:8180/job/xxxxxxxx/'},
          {'_class': 'hudson.model.FreeStyleProject',
           'color': 'red',
           'name': 'xxxxxxxx',
           'url': 'http://xxxxx:8180/job/xxxxxxxx/'},
          {'_class': 'hudson.model.FreeStyleProject',
           'color': 'blue',
           'name': 'xxxxxxxx',
           'url': 'http://xxxxx:8180/job/xxxxxxxx/'},
          {'_class': 'hudson.model.FreeStyleProject',
           'color': 'aborted',
           'name': 'xxxxxxxx',
           'url': 'http://xxxxx:8180/job/xxxxxxxx/'}]}
http://xxxxx:8180/
{'_class': 'hudson.model.Hudson',
 'assignedLabels': [{}],
 'description': None,
 'jobs': [{'_class': 'hudson.model.FreeStyleProject',
           'color': 'red',
           'name': 'xxxxx',
           'url': 'http://xxxxx:8180/job/xxxxx/'},
          {'_class': 'hudson.model.FreeStyleProject',
           'color': 'red',
           'name': 'xxxxx',
           'url': 'http://xxxxx:8180/job/xxxxx/'},
          {'_class': 'hudson.model.FreeStyleProject',
           'color': 'blue',
           'name': 'xxxxx',
           'url': 'http://xxxxx:8180/job/xxxxx/'},
          {'_class': 'hudson.model.FreeStyleProject',
           'color': 'aborted',
           'name': 'xxxxx',
           'url': 'http://xxxxx:8180/job/xxxxx/'}],
 'mode': 'NORMAL',
 'nodeDescription': 'the master Jenkins node',
 'nodeName': '',
 'numExecutors': 2,
 'overallLoad': {},
 'primaryView': {'_class': 'hudson.model.AllView',
                 'name': 'All',
                 'url': 'http://xxxxx:8180/'},
 'quietingDown': False,
 'slaveAgentPort': 0,
 'unlabeledLoad': {'_class': 'jenkins.model.UnlabeledLoadStatistics'},
 'useCrumbs': False,
 'useSecurity': True,
 'views': [{'_class': 'hudson.model.AllView',
            'name': 'All',
            'url': 'http://xxxxx:8180/'}]}


Traceback (most recent call last):
  File "zjenkins.py", line 223, in <module>
    handle.build_job()
  File "zjenkins.py", line 195, in build_job
    print mjob.get_params_list()
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/job.py", line 657, in get_params_list
    return [param['name'] for param in self.get_params()]
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/job.py", line 644, in get_params
    actions = (x for x in self._data[place] if x is not None)
KeyError: 'actions'
```
##### Sugestion
add invoke to Jenkins class, or give another interface to Jenkins to upload file, it can be convenient.
```
/*url: http://xxxxx:8180*/
  j = jenkinsapi.jenkins.Jenkins(self.config['jobs'][self.job_sub_name]['srvurl'],  self.config['jobs'][self.job_sub_name]['auth']['username'],  self.config['jobs'][self.job_sub_name]['auth']['token'])
/*url: none */
 mjob = job.Job(url=None, name=self.job_name, jenkins_obj=j)
print mjob.get_params_list()
 mjob.invoke(securitytoken=self.config['jobs'][self.job_sub_name]['auth']['token'] ,block=True, build_params=self.param[self.param['paramid']], files={str(self.config['jobs'][self.job_sub_name]['file_name']) : upload_file})
```

**Comment by lechat** [comment]
I am not sure if I undestood problem correctly.

You have job that has string parameter and file parameter. Then jenkinsapi fails on calling `job.get_param_list()`, right?

**Comment by lechat** [comment]
I've added test conditions for your problem into `systests/test_parametrized_builds.py`, but I cannot reproduce problem.
