### ISSUE TITLE
UrlEncode jobs names for get_jobs

### ISSUE THREAD

**Issue by claytantor** [pycontribs/jenkinsapi#529]
##### ISSUE TYPE
 - Bug Report

##### Jenkins VERSION
Page generated: Jan 9, 2017 5:53:21 AM UTCREST APIJenkins ver. 2.36

##### SUMMARY
Url being used for getjobs need to be encoded. When branches have names like feature/#4 job names are: Full project name: awsdoer/mb-awsdoer/feature%2F%231 and the URl to get to them are: /job/awsdoer/job/mb-awsdoer/job/feature%252F%25231/

##### EXPECTED RESULTS
when making the following call:

```
    jobs = jenkins.get_jobs()
    for job in jobs:
        print job
```

the key in the get_jobs should have an urlencode call made on so that the url that errors:

```
Traceback (most recent call last):
  File "t2.py", line 62, in <module>
    main(sys.argv[1:])
  File "t2.py", line 42, in main
    for job in jobs:
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/jenkinsapi/jobs.py", line 91, in iteritems
    for job in self.itervalues():
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/jenkinsapi/jobs.py", line 116, in itervalues
    yield Job(row['url'], row['name'], self.jenkins)
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/jenkinsapi/job.py", line 74, in __init__
    JenkinsBase.__init__(self, self.url)
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/jenkinsapi/job.py", line 98, in poll
    data = super(Job, self).poll(tree=tree)
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 59, in poll
    data = self._poll(tree=tree)
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 69, in _poll
    return self.get_data(url, tree=tree)
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 83, in get_data
    response.raise_for_status()
  File "/Users/claytongraham/data/venv/jenkinsdoer/lib/python2.7/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://myjenkins:8080/job/awsdoer/job/mb-awsdoer/job/feature%2F%231/api/python
```

is actually:

```
http://myjenkins:8080/job/awsdoer/job/mb-awsdoer/job/feature%252F%25231/
```

**Comment by lechat** [comment]
So you're saying that Jenkins now expects that job name will be urlencoded twice? I'd say that this is bug in Jenkins and better to be raised in Jenkins Jira.

**Comment by MrKiven** [comment]
same issue for me..

**Comment by lechat** [comment]
still... a bug in Jenkins.

**Comment by haitongz** [comment]
same issue for me..

**Comment by lechat** [comment]
Good to know. Why don't you raise that in Jenkins Jira?
