### ISSUE TITLE
New credential creation throws exception when it actually is successful

### ISSUE THREAD

**Issue by khornberg** [pycontribs/jenkinsapi#549]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION 
0.3.4

##### Jenkins VERSION
2.46.1

##### SUMMARY

Adding a credential raises an exception even when the credential creation was successful

##### EXPECTED RESULTS

Not raise an exception

##### ACTUAL RESULTS

JenkinsAPIException raised

##### USEFUL INFORMATION

```
from jenkinsapi.jenkins import Jenkins
from jenkinsapi.credential import SecretTextCredential
from jenkinsapi.custom_exceptions import JenkinsAPIException
from jenkinsapi.utils.crumb_requester import CrumbRequester

jenkins_url = 'http://localhost.imtapps.com:32773'

jenkins = Jenkins(
    jenkins_url,
    requester=CrumbRequester(
        baseurl=jenkins_url,
        username='test',
        password='test',
    )
)

print(jenkins.credentials._data)
for key in jenkins.credentials:
    print(key, )

jenkins.credentials['test'] = SecretTextCredential({
    'description': 'test creds',
    'secret': 'this is the secret token',
})


```

###Results in

```
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
  File "/.virtualenvs/build_automation/lib/python3.4/site-packages/jenkinsapi/credentials.py", line 112, in __setitem__
    raise JenkinsAPIException('Problem creating/updating credential.')
jenkinsapi.custom_exceptions.JenkinsAPIException: Problem creating/updating credential.
{'global': True, 'urlName': '_', 'fullDisplayName': 'System » Global credentials (unrestricted)', '_class': 'com.cloudbees.plugins.credentials.CredentialsStoreAction$DomainWrapper', 'displayName': 'Global credentials (unrestricted)', 'fullName': 'system/_', 'description': 'Credentials that should be available irrespective of domain specification to requirements matching.', 'credentials': {'10b3fe7e-f5b4-4736-b1e2-f966836073c9': <jenkinsapi.credential.SecretTextCredential object at 0x1059c8cc0>}}
test jenkins
```

### Except the exception

```
from jenkinsapi.jenkins import Jenkins
from jenkinsapi.credential import SSHKeyCredential, SecretTextCredential
from jenkinsapi.custom_exceptions import JenkinsAPIException
from jenkinsapi.utils.crumb_requester import CrumbRequester

jenkins_url = 'http://localhost.imtapps.com:32773'

jenkins = Jenkins(
    jenkins_url,
    requester=CrumbRequester(
        baseurl=jenkins_url,
        username='test',
        password='test',
    )
)

print(jenkins.credentials._data)
for key in jenkins.credentials:
    print(key, )

try:
    jenkins.credentials['test'] = SecretTextCredential({
        'description': 'test creds',
        'secret': 'this is the secret token',
    })
except JenkinsAPIException:
    pass

print(jenkins.credentials._data)
for key in jenkins.credentials:
    print(key, )
```

### Results in 

```
{'description': 'Credentials that should be available irrespective of domain specification to requirements matching.', 'fullDisplayName': 'System » Global credentials (unrestricted)', 'credentials': {'10b3fe7e-f5b4-4736-b1e2-f966836073c9': <jenkinsapi.credential.SecretTextCredential object at 0x106543b38>, 'acb8c8f6-8bf8-4b9a-b6f7-d8716cf267bb': <jenkinsapi.credential.SecretTextCredential object at 0x106543ef0>}, 'displayName': 'Global credentials (unrestricted)', 'urlName': '_', '_class': 'com.cloudbees.plugins.credentials.CredentialsStoreAction$DomainWrapper', 'global': True, 'fullName': 'system/_'}
test jenkins
test creds
{'description': 'Credentials that should be available irrespective of domain specification to requirements matching.', 'fullDisplayName': 'System » Global credentials (unrestricted)', 'credentials': {'10b3fe7e-f5b4-4736-b1e2-f966836073c9': <jenkinsapi.credential.SecretTextCredential object at 0x106557ef0>, '754799da-ef4b-422a-8fe0-9e9f18edcb14': <jenkinsapi.credential.SecretTextCredential object at 0x106543fd0>, 'acb8c8f6-8bf8-4b9a-b6f7-d8716cf267bb': <jenkinsapi.credential.SecretTextCredential object at 0x1065435c0>}, 'displayName': 'Global credentials (unrestricted)', 'urlName': '_', '_class': 'com.cloudbees.plugins.credentials.CredentialsStoreAction$DomainWrapper', 'global': True, 'fullName': 'system/_'}
test jenkins
test creds
test creds
```

From the above output, the credentials are in fact created. When I check on Jenkins the credentials are there as well.

**Comment by mellena1** [comment]
I'm seeing the same exception/message being triggered in the same situation. Its not consistent though, I will make one credential and it will work, but making another won't. 

It looks like the error is caused because `description` isn't in the credentials object when it does a check, although that was based on my quick look over so take that with a grain of salt.
