### ISSUE TITLE
BadStatusLine

### ISSUE THREAD

**Issue by iarspider** [pycontribs/jenkinsapi#566]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.3.3

##### Jenkins VERSION
2.46.3

##### SUMMARY

When starting the job with block=True, the script will sometimes fail with BadStatusLine exception

##### EXPECTED RESULTS

No exception

##### ACTUAL RESULTS

See stack trace below

##### USEFUL INFORMATION

Possibly related to this: https://github.com/requests/requests/issues/2364
(a rush condition between server closing the session on timeout and client
sending a request just before that timeout). 

Possible solution: catch that exception and retry the request.

```
Traceback (most recent call last):
  File "runme.py", line 14, in <module>
    lcgjenkinsAPI.build_and_install(target_packages, target_releases, wait=True)
  File "/afs/cern.ch/user/r/razumov/virtualenv/jenkins/lcgjenkinsAPI.py", line 463, in build_and_install
    res = build_package(name, releases, **kwargs)
  File "/afs/cern.ch/user/r/razumov/virtualenv/jenkins/lcgjenkinsAPI.py", line 405, in build_package
    param_func=get_build_params, policy=policy, ignore_fail=False, **kwargs)
  File "/afs/cern.ch/user/r/razumov/virtualenv/jenkins/lcgjenkinsAPI.py", line 327, in perform_build
    qi = lcg_release_m.invoke(build_params=params, cause="JenkinsAPI", combinations=combinations, block=wait)
  File "/afs/cern.ch/user/r/razumov/virtualenv/jenkins/MatrixJob.py", line 66, in invoke
    files=files, delay=delay)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/jenkinsapi/job.py", line 224, in invoke
    qi.block_until_complete(delay=delay)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/jenkinsapi/queue.py", line 139, in block_until_complete
    return build.block_until_complete(delay=delay)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/jenkinsapi/build.py", line 373, in block_until_complete
    while self.is_running():
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/jenkinsapi/build.py", line 355, in is_running
    data = self.poll(tree='building')
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 59, in poll
    data = self._poll(tree=tree)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/jenkinsapi/build.py", line 65, in _poll
    return self.get_data(url, params={'depth': self.depth}, tree=tree)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 79, in get_data
    response = requester.get_url(url, params)
  File "/afs/cern.ch/user/r/razumov/virtualenv/jenkins/requestor.py", line 44, in get_url
    resp = self.request.get(self._update_url_scheme(url), **requestKwargs)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/afs/cern.ch/user/r/razumov/.virtualenvs/jenkins/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

```

**Comment by ssbarnea** [comment]
#565 should have fixed that.

**Comment by iarspider** [comment]
Nope, #565 doesn't fix that. I didn't check that, but it looks like the retry counter doesn't get reset after a successful request, and eventually it fails again.
