### ISSUE TITLE
Syntax error after fresh install of jenkinsapi 0.3.4

### ISSUE THREAD

**Issue by drhelmer** [pycontribs/jenkinsapi#588]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.3.4

##### Jenkins VERSION
2.60.3.1

##### SUMMARY
Just installed jenkinsapi with pip, and tried the example python file for getting the server version, and it fails with   SyntaxError: invalid syntax

##### USEFUL INFORMATION
pip install jenkinsapi 

$cat jenk.py
from jenkinsapi.jenkins import Jenkins

def get_server_instance():
    jenkins_url = 'http://localhost:8080'
    server = Jenkins(jenkins_url, username = 'xxxxxx', password = 'xxxxxx')
    return server

if __name__ == '__main__':
    print get_server_instance().version

$ python jenk.py
Traceback (most recent call last):
  File "jenk.py", line 1, in <module>
    from jenkinsapi.jenkins import Jenkins
  File "/usr/lib/python2.6/site-packages/jenkinsapi/__init__.py", line 49, in <module>
    from jenkinsapi import (
  File "/usr/lib/python2.6/site-packages/jenkinsapi/api.py", line 15, in <module>
    from jenkinsapi.jenkins import Jenkins
  File "/usr/lib/python2.6/site-packages/jenkinsapi/jenkins.py", line 12, in <module>
    from jenkinsapi.jobs import Jobs
  File "/usr/lib/python2.6/site-packages/jenkinsapi/jobs.py", line 6, in <module>
    from jenkinsapi.job import Job
  File "/usr/lib/python2.6/site-packages/jenkinsapi/job.py", line 10, in <module>
    from jenkinsapi.build import Build
  File "/usr/lib/python2.6/site-packages/jenkinsapi/build.py", line 109
    return {pair['name']: pair['value'] for pair in parameters}
                                          ^
SyntaxError: invalid syntax
```

```

**Comment by lechat** [comment]
Sorry, but support for python 2.6 in this library was dropped long time ago.

**Comment by drhelmer** [comment]
Then I would suggest to chenge the docs 👍 
Python versions

The project have been tested and working on Python 2.7, 3.3 and 3.4. It was tested previously on Python 2.6, so it may work on this version too.
