### ISSUE TITLE
Failed to request job api

### ISSUE THREAD

**Issue by wenchma** [pycontribs/jenkinsapi#650]
##### ISSUE TYPE
 - Bug Report

##### Jenkins VERSION
```
>>> J.version
'2.121.1'
```

##### SUMMARY
```
>>> job=J['demo']
ERROR:root:Failed request at http://192.168.100.236:8080/jenkins/job/demo/api/python with params: None 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkins.py", line 236, in __getitem__
    return self.jobs[jobname]
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jobs.py", line 86, in __getitem__
    return Job(job_data['url'], job_data['name'], self.jenkins)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/job.py", line 68, in __init__
    JenkinsBase.__init__(self, self.url)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/job.py", line 92, in poll
    data = super(Job, self).poll(tree=tree)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
    data = self._poll(tree=tree)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 67, in _poll
    return self.get_data(url, tree=tree)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 81, in get_data
    response.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://192.168.100.236:8080/jenkins/job/demo/api/python
```

##### EXPECTED RESULTS
successful to get the job

##### ACTUAL RESULTS
failed to get the job

##### USEFUL INFORMATION

```
>>> J.keys()
['demo', 'http:/192.168.100.236:8080/job', 'wenchma', 'http:/192.168.100.236:8080/job']
```

**Comment by lechat** [comment]
It looks that user doesn't have access to read job definition.
