### ISSUE TITLE
why remove content lines from jobs.py near line 149 in version 0.3.6?

### ISSUE THREAD

**Issue by ward-peng** [pycontribs/jenkinsapi#673]
```
version 0.3.6 
config = str(config)  # cast unicode in case of Python 2

version 0.3.3
try:
     if isinstance(config, unicode):  # pylint: disable=undefined-variable
                config = str(config)
except NameError:
            # Python2 already a str
            pass
```

**Comment by lechat** [comment]
Is that causing any troubles?

**Comment by ward-peng** [comment]
> Is that causing any troubles?

yes ,when i send the param config within chinese characters (type bytes) 
it raise some error like this:
______________
Traceback (most recent call last):
  File "/Users/yunshao/Code/sonar_auto_access/sonar/bulk_remove_sonar_jobs.py", line 215, in <module>
    bulk_removed_sonar_jobs(old_sonar_url, new_sonar_url, 'sonar')
  File "/Users/yunshao/Code/sonar_auto_access/sonar/bulk_remove_sonar_jobs.py", line 183, in bulk_removed_sonar_jobs
    new_jenkins.create_job(key+"new", new_xml_content)
  File "/Users/yunshao/Code/envlist/sonar_venv/lib/python3.7/site-packages/jenkinsapi/jenkins.py", line 158, in create_job
    return self.jobs.create(jobname, xml)
  File "/Users/yunshao/Code/envlist/sonar_venv/lib/python3.7/site-packages/jenkinsapi/jobs.py", line 159, in create
    params=params
  File "/Users/yunshao/Code/envlist/sonar_venv/lib/python3.7/site-packages/jenkinsapi/utils/requester.py", line 128, in post_xml_and_confirm_status
    url, params=params, data=data, headers=headers, valid=valid)
  File "/Users/yunshao/Code/envlist/sonar_venv/lib/python3.7/site-packages/jenkinsapi/utils/requester.py", line 151, in post_and_confirm_status
    response.text.encode('UTF-8')
jenkinsapi.custom_exceptions.JenkinsAPIException: Operation failed. url=http://abqa.ci.ee.test.sankuai.com/job/abqa/job/sonar_test_yun/createItem?name=box-base-client_auto_static_analyzenew, data=b'<?xml v
________________
when I comment this line `config = str(config)  # cast unicode in case of Python 2` or use version 0.3.3 use `        try:
            if isinstance(config, unicode):  # pylint: disable=undefined-variable
                config = str(config)
        except NameError:
            # Python2 already a str
            pass`
it work success,
can revert this code ?

**Comment by lechat** [comment]
Please submit pull request for this change.
