### ISSUE TITLE
403 and Value errors when using username & token in server url

### ISSUE THREAD

**Issue by ryanm101** [pycontribs/jenkinsapi#677]
##### ISSUE TYPE
 - Bug Report

##### Jenkinsapi VERSION
0.3.7

##### Jenkins VERSION
2.121.3

##### SUMMARY

When using a username & Token combo to invoke jobs and query certain statuses I get back errors

* Getting back 403 Client error after querying for status
* Getting back ValueError after invoking a build

##### EXPECTED RESULTS
JOB queue / status

##### ACTUAL RESULTS
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:

##### USEFUL INFORMATION
```
from jenkinsapi import jenkins

j = jenkins.Jenkins('https://<username>:<token>@<jenkinsurl>')
jb = j.get_job('Build/MyJOB/build/xxx')

jb.invoke()

jb.is_queued_or_running()

```

`jb.is_queued()` works fine
`jb.is_running()` fails as above

What is interesting is that when I create the jenkins instance i use: `'https://<username>:<token>@<jenkinsurl>'` but the url that is failing in the response is `'https://<jenkinsurl>'`

Digging deeper the issue seems to lie in `https://github.com/pycontribs/jenkinsapi/blob/0.3.7/jenkinsapi/job.py` in the `get_build_dict(self)` method. 
This method is returning the dict containing `{'job#': 'https://<jenkinsurl>/job/Build/job/MYJOB/job/build%2Fxxx/16/' }` which is missing the credentials. 

Proof of Fix:
```
from jenkinsapi import jenkins

j = jenkins.Jenkins('https://<username>:<token>@<jenkinsurl>')
jb = j.get_job('Build/MyJOB/build/xxx')

# Falsify the return so it returns a 'valid' url
jb.__dict__["get_build_dict"] = (lambda: dict( [(16, 'https://<username>:<token>@<jenkinsurl>/job/Build/job/MYJOB/job/build%2Fxxx/16/' )] ))

jb.is_queued_or_running()

```

### Tracebacks

`jb.invoke()` result:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    jb.invoke()
  File "/venv/lib/python3.7/site-packages/jenkinsapi/job.py", line 215, in invoke
    raise ValueError("Not a Queue URL: %s" % redirect_url)
ValueError: Not a Queue URL: https://<jenkinsurl>/queue/item/44196/
```

`jb.is_queued_or_running` result:
```
jb.is_queued_or_running()
ERROR:root:Failed request at https://<jenkinsurl>/job/Build/job/MYJOB/job/build%2Fxxx/15/api/python with params: {'depth': 1}
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    jb.is_queued_or_running()
  File "/venv/lib/python3.7/site-packages/jenkinsapi/job.py", line 440, in is_queued_or_running
    return self.is_queued() or self.is_running()
  File "/venv/lib/python3.7/site-packages/jenkinsapi/job.py", line 462, in is_running
    build = self.get_last_build_or_none()
  File "/venv/lib/python3.7/site-packages/jenkinsapi/job.py", line 364, in get_last_build_or_none
    return self.get_last_build()
  File "/venv/lib/python3.7/site-packages/jenkinsapi/job.py", line 353, in get_last_build
    return self.get_build(bn)
  File "/venv/lib/python3.7/site-packages/jenkinsapi/job.py", line 396, in get_build
    return Build(url, buildnumber, job=self)
  File "/venv/lib/python3.7/site-packages/jenkinsapi/build.py", line 56, in __init__
    JenkinsBase.__init__(self, url)
  File "/venv/lib/python3.7/site-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/venv/lib/python3.7/site-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
    data = self._poll(tree=tree)
  File "/venv/lib/python3.7/site-packages/jenkinsapi/build.py", line 63, in _poll
    return self.get_data(url, params={'depth': self.depth}, tree=tree)
  File "/venv/lib/python3.7/site-packages/jenkinsapi/jenkinsbase.py", line 81, in get_data
    response.raise_for_status()
  File "/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://<jenkinsurl>/job/Build/job/MYJOB/job/build%2Fxxx/15/api/python?depth=1
```

**Comment by lechat** [comment]
You need to use `CrumbsRequester`: https://github.com/pycontribs/jenkinsapi/blob/master/examples/how_to/use_crumbs.py

**Comment by ryanm101** [comment]
Similar error:
`
j = Jenkins(url, username=username, password=passwd, requester=CrumbRequester(baseurl=url, username=username, password=passwd))`

```
ERROR:root:Failed request at https://<jenkinserver>/api/python with params: {'tree': 'jobs[name,color,url]'} jobs[name,color,url]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    j = Jenkins(url, username=username, password=passwd, requester=CrumbRequester(baseurl=url, username=username, password=passwd))
  File "/venv/lib/python3.7/site-packages/jenkinsapi/jenkins.py", line 63, in __init__
    JenkinsBase.__init__(self, baseurl, poll=not lazy)
  File "/venv/lib/python3.7/site-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/venv/lib/python3.7/site-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
    data = self._poll(tree=tree)
  File "/venv/lib/python3.7/site-packages/jenkinsapi/jenkins.py", line 68, in _poll
    if not tree else tree)
  File "/venv/lib/python3.7/site-packages/jenkinsapi/jenkinsbase.py", line 81, in get_data
    response.raise_for_status()
  File "/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://<jenkinsserver>/api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D
```

Browsing to `https://<jenkinsserver>/api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D` prompts for login and returns

```
{"_class":"hudson.model.Hudson","jobs":[{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"Build","url":"https://<jenkinsserver>/job/Build/"},{"_class":"org.jenkinsci.plugins.workflow.job.WorkflowJob","name":"universal-jenkins-cleanup","url":"https://<jenkinsserver>/job/universal-jenkins-cleanup/","color":"blue"},{"_class":"hudson.model.FreeStyleProject","name":"update-jobs","url":"https://<jenkinsserver>/job/update-jobs/","color":"blue"}]}
```

Using `wget -q --auth-no-challenge --user ${user}--password ${PASSWD} --output-document - \
'https://<jenkinsserver>/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'

returns a crumb as expected
