### ISSUE TITLE
create_job raises UnknownJob error when creating job with bitbucket source

### ISSUE THREAD

**Issue by chrismaes87** [pycontribs/jenkinsapi#714]
##### ISSUE TYPE
Bug Report

##### Jenkinsapi VERSION
0.3.9

##### Jenkins VERSION
2.182

##### SUMMARY
create_job raises and UnknownJob error while the job seems to be created correctly.

##### EXPECTED RESULTS
create_job to succeed

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/workspace/ci-e2e/virtualenv/lib/python3.6/site-packages/jenkinsapi/jenkins.py", line 173, in create_job
    return self.jobs.create(jobname, xml)
  File "/home/chris/workspace/ci-e2e/virtualenv/lib/python3.6/site-packages/jenkinsapi/jobs.py", line 163, in create
    return self[job_name]
  File "/home/chris/workspace/ci-e2e/virtualenv/lib/python3.6/site-packages/jenkinsapi/jobs.py", line 88, in __getitem__
    raise UnknownJob(job_name)
jenkinsapi.custom_exceptions.UnknownJob: 'test'
```

##### USEFUL INFORMATION
```
JENKINS_JOB_TEMPLATE = """<?xml version='1.1' encoding='UTF-8'?>
<org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject plugin="workflow-multibranch@2.20">
  <actions/>
  <description></description>
  <properties>
    <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.3.1">
      <dockerLabel/>
      <registry plugin="docker-commons@1.13"/>
    </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
  </properties>
  <folderViews class="jenkins.branch.MultiBranchProjectViewHolder" plugin="branch-api@2.0.20">
    <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
  </folderViews>
  <healthMetrics/>
  <icon class="jenkins.branch.MetadataActionFolderIcon" plugin="branch-api@2.0.20">
    <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
  </icon>
  <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.5.1">
    <pruneDeadBranches>true</pruneDeadBranches>
    <daysToKeep>7</daysToKeep>
    <numToKeep>-1</numToKeep>
  </orphanedItemStrategy>
  <triggers>
    <com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger plugin="cloudbees-folder@6.5.1">
      <spec>H H(0-6) * * *</spec>
      <interval>86400000</interval>
    </com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger>
  </triggers>
  <disabled>false</disabled>
  <sources class="jenkins.branch.MultiBranchProject$BranchSourceList" plugin="branch-api@2.0.20">
    <data>
      <jenkins.branch.BranchSource>
        <source class="com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource" plugin="cloudbees-bitbucket-branch-source@2.2.12">
          <id>a2d4bcda-6141-4af2-8088-39139a147902</id>
          <serverUrl>****</serverUrl>
          <credentialsId>****</credentialsId>
          <repoOwner>{project}</repoOwner>
          <repository>{repository}</repository>
          <traits>
            <com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait>
              <strategyId>1</strategyId>
            </com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait>
            <com.cloudbees.jenkins.plugins.bitbucket.OriginPullRequestDiscoveryTrait>
              <strategyId>1</strategyId>
            </com.cloudbees.jenkins.plugins.bitbucket.OriginPullRequestDiscoveryTrait>
            <com.cloudbees.jenkins.plugins.bitbucket.ForkPullRequestDiscoveryTrait>
              <strategyId>1</strategyId>
              <trust class="com.cloudbees.jenkins.plugins.bitbucket.ForkPullRequestDiscoveryTrait$TrustTeamForks"/>
            </com.cloudbees.jenkins.plugins.bitbucket.ForkPullRequestDiscoveryTrait>
            <com.cloudbees.jenkins.plugins.bitbucket.SSHCheckoutTrait>
              <credentialsId>jenkins-stash</credentialsId>
            </com.cloudbees.jenkins.plugins.bitbucket.SSHCheckoutTrait>
          </traits>
        </source>
        <strategy class="jenkins.branch.DefaultBranchPropertyStrategy">
          <properties class="empty-list"/>
        </strategy>
      </jenkins.branch.BranchSource>
    </data>
    <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
  </sources>
  <factory class="org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory">
    <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
    <scriptPath>Jenkinsfile</scriptPath>
  </factory>
</org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>"""

jenkins = Jenkins("http://localhost:8080", requester=CrumbRequester(baseurl="http://localhost:8080"))
jenkins.create_job(jobname="test", xml=TEMPLATE.format(project="project", repository="repository")
```

**Comment by chrismaes87** [comment]
I seems like the problem is that jenkinsapi cannot cope with multibranch pipelines... Once I run "Scan Multibranch Pipeline Now", then the jobs exist (one for each branch), but not before.

jenkinsapi doesn't seem to allow me to trigger the scan either...

**Comment by chrismaes87** [comment]
after playing around with the code and a test instance; it seems like jenkinsapi isn't ready to manage multibranch pipelines at all. Would that be an interesting feature to develop? I am willing to implement and test this, but I suppose some discussions up front might be constructive.

Multiple remarks and ideas:

- I'm not sure create_job() is extensible to create also multibranch pipeline jobs. create_job() will return the job object just created. a multibranch pipeline mostly contains multiple jobs. Then what would be the return value?
- a new method create_multibranch_pipeline() might automatically launch the 'scan multibranch pipeline now' and afterwards return a list of all jobs that were created?
- note that there exist also **Bitbucket Team/Project** and **Github Organisation** jobs; which would contain even more jobs :)
- in jenkinsapi, jobs are stored by name. When working with multibranch pipelines you can have jobs with the same name. I had a simple repository with master branch, so a job "test/master" and a job "master" was created. If I add more repositories; many jobs with the name "master" would exist. Not sure if that is a real problem though for the moment.

**Comment by lechat** [comment]
I don't use those plugins, so it is not a pain point for me. But I gladly accept code that fixes issues with such plugins.

**Comment by chrismaes87** [comment]
I just created you a pull-request yesterday for this; I'll close this issue.

**Comment by chrismaes87** [comment]
pull-request: https://github.com/pycontribs/jenkinsapi/pull/715
