### ISSUE TITLE
jenkinsapi.custom_exceptions.UnknownJob : 0.3.11

### ISSUE THREAD

**Issue by puranikamey** [pycontribs/jenkinsapi#822]
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.3.11

##### Jenkins VERSION
 2.362

##### SUMMARY
Performaing simple empty job creation using EMPTY_FOLDER_XML.
getting following error 
  File "/usr/local/lib/python3.9/site-packages/jenkinsapi/jobs.py", line 89, in __getitem__
    raise UnknownJob(job_name)
jenkinsapi.custom_exceptions.UnknownJob:Account1scsav

##### EXPECTED RESULTS
Should be able to create folder in jenkins. 

##### ACTUAL RESULTS

Error: 
/usr/local/bin/python3 /Users/apuranik/Documents/test2e.py
Traceback (most recent call last):
  File "/Users/apuranik/Documents/test2e.py", line 10, in <module>
    folder = server.create_job("Account1scsav", jenkins.EMPTY_FOLDER_XML)
  File "/usr/local/lib/python3.9/site-packages/jenkinsapi/jenkins.py", line 185, in create_job
    return self.jobs.create(jobname, xml)
  File "/usr/local/lib/python3.9/site-packages/jenkinsapi/jobs.py", line 166, in create
    return self[job_name]
  File "/usr/local/lib/python3.9/site-packages/jenkinsapi/jobs.py", line 89, in __getitem__
    raise UnknownJob(job_name)
jenkinsapi.custom_exceptions.UnknownJob: 'Account1scsav'

##### USEFUL INFORMATION

```
Code :
from jenkinsapi.jenkins import Jenkins
from jenkinsapi.utils.crumb_requester import CrumbRequester
import jenkins

jenkins_url = 'http://localhost:8080'
crumb=CrumbRequester(username='admin', password=test@1234', baseurl=jenkins_url)
server = Jenkins(jenkins_url, username='admin', password='test@1234', requester=crumb)

folder = server.create_job("Account1scsav", jenkins.EMPTY_FOLDER_XML)
```

**Comment by puranikamey** [comment]
Is this is a bug? I tried downgrading to v 0.3.9 but came across alot of crumb issues.

**Comment by puranikamey** [comment]
python version 3.9
